### ISSUE TITLE
target/tmp/js folder (contaning modernizr.js) seems to be include in code coverage report

### ISSUE THREAD

**Issue by jensborch** [Nykredit/gript#70] opened 2016-04-13 13:32 UTC
On Jenkins the target/tmp/js folder (contaning modernizr.js) seems to be include in code coverage report. This is probably an error.

**Comment by Mortenagoda** [comment] 2016-04-25 10:18
I Just experienced this too. I agree. Only project sources should be included in the coverage report.

**Comment by jotka** [comment] 2016-04-25 10:57
ok, but target/tmp/js contains the javascripts coming from the typescript sources, so It needs to be included in the coverage. However, I can exclude the modernizr.js.

**Comment by hindsholm** [comment] 2016-06-13 16:36
We have the same problem, but we also get all of bower_components included in our code coverage, see e.g. http://jenkins/job/38/job/39/job/mitnykredit%20feature/399/cobertura/
The problem is, that `karma.preprocessors` has a default value of `'!(patch)/**/!(*_test).js': ['coverage']` which cannot be overridden, it can only be appended to.

**Comment by hindsholm** [comment] 2016-06-27 13:26
Fix suggested in #83

**Comment by jotka** [comment] 2016-06-27 15:05
Merged the fix thanks - release today or tomorrow.

**Closed by jotka** 2016-06-27 15:05 UTC

**Comment by jotka** [comment] 2016-06-27 15:34
published as 0.0.53
